# Jekyll配置
title: PubMed公共卫生专业每日动态
description: 汇聚公共卫生领域最新研究成果与行业动态
url: "https://gcp-lopo.github.io"
baseurl: "/pubmed-public-health"

# 自定义变量
articles:

# Build settings
future: true
markdown: kramdown

# 历史文章存档集合
future: true
collections:
  archives:
    output: true
    sort_by: date
    reverse: true
    permalink: /archives/:path/
    path: _archives
    defaults:
      - scope:
          path: "_archives"
          type: "archives"
        values:
          layout: "archive"